### ISSUE TITLE
Can't deploy to cloudflare

### ISSUE THREAD

**Issue by tina-hello** [serverless-dns/serverless-dns#3]
On deploying (why the link on the readme lead to non-existent repo?), I got

> Creating the secret for script name serverless-dns
> Worker serverless-dns doesn't exist in the API yet. Creating a draft Worker so we can create new secret.
> Error: No such file or directory (os error 2)

**Comment by santhosh-ponnusamy** [comment]
@tina-hello issue has been fixed, you can try now by clicking deploy button on https://github.com/serverless-dns/serverless-dns which will fork serverless-dns code to your git account and deploy to your cloudflare account.

**Comment by tina-hello** [comment]
Nah, still doesn't work https://github.com/tina-hello/serverless-dns-1/runs/2576307710?check_suite_focus=true

I've actually fix the link myself, without it I won't even get to reach the building stage.

I've tried deploying my own project to see if it's the problem with my Github/Cloudflare, yet they work. I see your code talks about AWS, is it necessary?

**Comment by santhosh-ponnusamy** [comment]
hi
Issue has been resolved there was a problem in setting a secret variable
before the worker initialization now the secrets are set after worker
initialization.
Try it now.
Its AWS Credentials which is set to null now, it will be used in future for
user dns logging and dns analytics.

**Comment by tina-hello** [comment]
Thank you @santhosh-ponnusamy, it now deploys successfully and answers requests on POST, but #2 happens with GET even for non-stamped URLs

**Comment by santhosh-ponnusamy** [comment]
Oh great, GET request implementation is not yet done, will update once it's
done.
